### ISSUE TITLE
Error creating new app

### ISSUE THREAD

**Issue by john-prowell** [qodesmith/create-new-app#2]
Enter a name for your app: react-test-two

Pressing `enter` defaults to no for the following...

Would you like to include Redux? [y, n] y
Would you like to include Redux First Router? [y, n] y
Would you like to include an Express server? [y, n] y
Would you like to include MongoDB? [y, n] y

Creating a new app in C:\Users\dtx\Projects\test-create-new-app-delete/react-test-two.
{ Error: ENOENT: no such file or directory, mkdir 'C:\Users\dtx\Projects\test-create-new-app-delete\react-test-two\C:\Users\dtx\AppData\Roaming\npm\node_modules\create-new-app\files\api'
    at fs.mkdirSync (fs.js:885:18)
    at copyTree (C:\Users\dtx\AppData\Roaming\npm\node_modules\create-new-app\modules\copyTree.js:15:3)
    at createFiles (C:\Users\dtx\AppData\Roaming\npm\node_modules\create-new-app\main.js:338:12)
    at letsGo (C:\Users\dtx\AppData\Roaming\npm\node_modules\create-new-app\main.js:158:3)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\Users\\dtx\\Projects\\test-create-new-app-delete\\react-test-two\\C:\\Users\\dtx\\AppData\\Roaming\\npm\\node_modules\\create-new-app\\files\\api' }

**Comment by qodesmith** [comment]
@john-prowell Hi, don't know why I'm seeing this 10 days later. Gotta check my alerts. Anyways, can you upgrade to the latest and try now? If it's still happening, let me know. Also, so you know, I've removed Redux First Router in favor of React Router. Just an FYI.

**Comment by qodesmith** [comment]
I see that you're on a Windows machine. I'll try and test this today on a PC and see if I get the same error.

**Comment by john-prowell** [comment]
@qodesmith I installed the latest version and tried running it again but received the following error message: 

`Enter a name for your app: awesomeness

Pressing `enter` defaults to no for the following...

Would you like to include Redux? [y, n] y
Would you like to include React Router? [y, n] y
Would you like to include an Express server? [y, n] y
Would you like to include MongoDB? [y, n] y

Creating a new app in C:\Users\dtx\Projects/awesomeness.
{ Error: ENOENT: no such file or directory, mkdir 'C:\Users\dtx\Projects/awesomeness/C:\Users\dtx\AppData\Roaming\npm\node_modules\create-new-app\files\api'
    at fs.mkdirSync (fs.js:874:3)
    at copyTree (C:\Users\dtx\AppData\Roaming\npm\node_modules\create-new-app\modules\copyTree.js:15:3)
    at createFiles (C:\Users\dtx\AppData\Roaming\npm\node_modules\create-new-app\main.js:338:12)
    at letsGo (C:\Users\dtx\AppData\Roaming\npm\node_modules\create-new-app\main.js:158:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path:
   'C:\\Users\\dtx\\Projects/awesomeness/C:\\Users\\dtx\\AppData\\Roaming\\npm\\node_modules\\create-new-app\\files\\api' }`

It does create the folder for the app with just the files:
.env
.gitignore
package.json
postcss.config.js
README.md,
server.js,
webpack.config.js

No other folders.

Also, the `cna <app-name> --sandbox` does work with no errors.
I'm using Windows 10.

**Comment by john-prowell** [comment]
Thanks for adding the option for React Router!

**Comment by qodesmith** [comment]
@john-prowell Sorry for the delay with this. My only access to a windows machine is at work and I'm behind fort-knox-like firewalls. Can you try uninstalling then reinstalling again? I've experienced similar issues on my Mac and that did the trick:

`npm r -g create-new-app`
then...
`npm i -g create-new-app`

Let me know if you still have the same issue. Gonna keep trying here at work...

**Comment by john-prowell** [comment]
@qodesmith I followed your instructions and that did the trick! I really like how you commented everything and included links. Thank you.

**Comment by qodesmith** [comment]
@john-prowell Awesome! And you're welcome :) I wanted this project to not only serve the purpose of creating new React applications but also as a learning tool if anyone peeked under the hood or combed through the generated code.
